version: '3.8'

networks:
  redis-network:
    driver: bridge
    external: true

services:
  msvc-gateway-server:
    build: .
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - app-logs:/logs
    networks:
      redis-network:
        aliases:
          - msvc-gateway-server

volumes:
  app-logs:
