version: '3.8'

networks:
  redis-network:
    driver: bridge
    external: true

services:
  eureka-server:
    image: eureka-server_app
    build: .
    ports:
      - "8761:8761"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - app-logs:/logs
    networks:
      - redis-network

volumes:
  app-logs:
