spring.application.name=gateway-service
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Habilitar discovery
spring.cloud.discovery.enabled=true
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

logging.level.org.springframework.security=DEBUG

jwt.secret.key = 123456789123456789123456789123456789123456a

management.tracing.sampling.probability=1.0