version: '3.8'

networks:
  redis-network:
    external: true

services:
  config-server:
    image: config-server_app
    build: .
    ports:
      - "8888:8888"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - app-logs:/logs
      - ./config:/config
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/config
    networks:
      - redis-network

volumes:
  app-logs:
