sonar.projectKey=auth-service
sonar.projectName=Auth Service
sonar.projectVersion=1.0

# Código fuente y tests
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.language=java
sonar.sourceEncoding=UTF-8

# Compilados
sonar.java.binaries=target/classes

# Reportes de cobertura de JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Reportes JUnit
sonar.junit.reportPaths=target/surefire-reports

# (Opcional) excluir DTOs o clases irrelevantes del análisis
sonar.exclusions=**/dto/**,**/config/**

# (Opcional) token si no lo pasás por parámetro
sonar.token=squ_b610f511f57c1739fa16f3654b9b9f503c696b92
