spring.application.name=service-accreditation
server.port=8081

eureka.client.serviceUrl.defaultZone:http://eureka-server:8761/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${spring.cloud.client.hostname}
#eureka.instance.use-ip-address=true

eureka.instance.instance-id=${spring.application.name}:${server.port}

management.tracing.sampling.probability=1.0

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

resilience4j.circuitbreaker.instances.default.failureRateThreshold=50
resilience4j.circuitbreaker.instances.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.default.slidingWindowSize=10
resilience4j.circuitbreaker.instances.default.waitDurationInOpenState=120000

resilience4j.circuitbreaker.instances.save.failureRateThreshold=50
resilience4j.circuitbreaker.instances.save.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.save.slidingWindowSize=10
resilience4j.circuitbreaker.instances.save.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.save.recordExceptions=com.cavallaro.kafka.exception.AccreditationServiceException

spring.kafka.bootstrap-servers=kafka:29092