spring.application.name=config-server
server.port=8888

#spring.cloud.config.server.git.uri=file:///C:/workspace/accenture-contents/salespoints/config

spring.profiles.active= native
spring.cloud.config.server.native.search-locations:file:/config

spring.security.user.name=
spring.security.user.password=
management.endpoints.web.exposure.include=*
security.basic.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

management.tracing.sampling.probability=1.0