spring.application.name=cost-service
server.port=8082

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret.key = 123456789123456789123456789123456789123456a

# Dirección del servidor Eureka (en este caso, Eureka Server corre en localhost:8761)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Habilitar registro en Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Evita errores por hostname si estás trabajando localmente
eureka.instance.prefer-ip-address=true

management.tracing.sampling.probability=1.0