spring:
  application:
    name: service-salepoint
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  datasource:
    url: jdbc:h2:file:/data/h2/sellingpointsdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  # Configuración JWT
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
server:
  port: 8080

#cache:
  #sellingPoints:
    #maxSize: 10000
    #expireAfterWrite: 10000
  #sellingCosts:
    #maxSize: 10000
    #expireAfterWrite: 10000

logging:
  file:
    name: /logs/application.log
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.cache: DEBUG
    org.springframework.security: DEBUG
