spring:
  application:
    name: msvc-gateway-server
  security:
    oauth2:
      authorization-server:
        issuer-url: http://service-oauth:9100
      resourceserver:
        jwt:
          jwk-set-uri: http://service-oauth:9100/oauth2/jwks
      client:
        registration:
          client-app:
            provider: spring
            client-id: gateway-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/authorized
            scope:
              - openid
              - profile
            client-name: client-app
        provider:
          spring:
            issuer-uri: http://service-oauth:9100
            authorization-uri: http://localhost:9100/oauth2/authorize
            token-uri: http://service-oauth:9100/oauth2/token

  cloud:
    gateway:
      mvc:
        routes:
          - id: service-oauth
            uri: lb://service-oauth
            predicates:
              - Path=/api/security/**
            filters:
              - StripPrefix=2
          - id: service-accreditation
            uri: lb://service-accreditation
            predicates:
              - Path=/api/accreditations/**
            filters:
              - StripPrefix=1
              - PrefixPath=/api/v1
          - id: service-salepoint
            uri: lb://service-salepoint
            predicates:
              - Path=/api/selling-points/**
            filters:
              - StripPrefix=1
              - PrefixPath=/api/v1
          - id: service-costs
            uri: lb://service-salepoint
            predicates:
              - Path=/api/costs/**
            filters:
              - StripPrefix=1
              - PrefixPath=/api/v1
          - id: service-users
            uri: lb://service-users
            predicates:
              - Path=/api/users/**
            filters:
              - StripPrefix=2
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG