spring.application.name=msvc-gateway-server
server.port=8090

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${spring.cloud.client.hostname}
#eureka.instance.use-ip-address=true

eureka.instance.instance-id=${spring.application.name}:${server.port}

#spring.security.oauth2.authorization-server.issuer-url=http://localhost:9100

management.tracing.sampling.probability=1.0